In [1]:
import pandas as pd
import numpy as np

## **Series is 1D and DataFrames are 2D objects**

In [2]:
# can we have multiple index 
# Multiindex series (also Known as Hierarchical Indexing)

In [3]:
# How to Create multiindex object 
#1) pd.Multiindex.from_tuples()
idx_values = [('cse',2019),('cse',2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]
multiindex=pd.MultiIndex.from_tuples(idx_values)
print(multiindex.levels[0])
print(multiindex.levels[1])

Index(['cse', 'ece'], dtype='str')
Index([2019, 2020, 2021, 2022], dtype='int64')

In [4]:
# 2) pd.Multiindex.from_product()
pd.MultiIndex.from_product([['cse','ece'],[2019,2020,2021,2022]])

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [5]:
# Creating a series with multiindex object
s = pd.Series([1,2,3,4,5,6,7,8,],index=multiindex)
s

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [6]:
# How to Fetch items from such a series
s['cse']

2019    1
2020    2
2021    3
2022    4
dtype: int64

In [7]:
# This is multi Index series is 2d because to fetch a particular value we need two values

In [8]:
# unstack : Convert a multi index series into DataFrame
temp = s.unstack()
temp

     2019  2020  2021  2022
cse     1     2     3     4
ece     5     6     7     8

In [9]:
# stack : (unstack opposite)
temp.stack()

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [10]:
# Then What is a point of MultiIndex series ?
# ----> Through this same idea we can represent a higher dimension data into lower dimensions (3d -- 2d represent)

In [11]:
# MultiIindex DataFrame
branch_df1 = pd.DataFrame(
[       [1,2],
        [3,4],
        [5,6],
        [7,8],
        [9,10],
        [11,12],
        [13,14],
        [15,16],
    ],
    index= multiindex,
    columns=['avg_package','students']
)
branch_df1

          avg_package  students
cse 2019            1         2
    2020            3         4
    2021            5         6
    2022            7         8
ece 2019            9        10
    2020           11        12
    2021           13        14
    2022           15        16

In [12]:
branch_df1.loc['ece']

      avg_package  students
2019            9        10
2020           11        12
2021           13        14
2022           15        16

In [13]:
branch_df1['avg_package']

cse  2019     1
     2020     3
     2021     5
     2022     7
ece  2019     9
     2020    11
     2021    13
     2022    15
Name: avg_package, dtype: int64

In [14]:
# At implementation level pandas treat columns and index as same

In [15]:
# Multiindex df from columns prespective
branch_df2 = pd.DataFrame([
    [1,2,0,0],
    [3,4,0,0],
    [5,6,0,0],
    [7,8,0,0]
],index=[2019,2020,2021,2022],
columns= pd.MultiIndex.from_product([['delhi','mumbai'],['avg_package','students']]))
branch_df2 # 3d data --- Represent 2D

           delhi               mumbai
     avg_package students avg_package students
2019           1        2           0        0
2020           3        4           0        0
2021           5        6           0        0
2022           7        8           0        0

In [16]:
branch_df2['delhi']

      avg_package  students
2019            1         2
2020            3         4
2021            5         6
2022            7         8

In [17]:
branch_df2['delhi']['avg_package']

2019    1
2020    3
2021    5
2022    7
Name: avg_package, dtype: int64

In [18]:
branch_df2.loc[2019]

delhi   avg_package    1
        students       2
mumbai  avg_package    0
        students       0
Name: 2019, dtype: int64

In [19]:
# MultiIndex df  in terms of both cols and index
branch_df3 = pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0],
        [9,10,0,0],
        [11,12,0,0],
        [13,14,0,0],
        [15,16,0,0],
    ],
    index= multiindex,
    columns=pd.MultiIndex.from_product([['delhi','mumbai'],['avg_package','students']])
)
branch_df3

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

In [20]:
branch_df3['delhi']['avg_package']

cse  2019     1
     2020     3
     2021     5
     2022     7
ece  2019     9
     2020    11
     2021    13
     2022    15
Name: avg_package, dtype: int64

## **Stacking and Unstacking**

In [21]:
branch_df2.unstack()## Index becomes columns and Columns become Multiindex...
# level 0 is avg_package,and students
# level 1 year......

delhi   avg_package  2019    1
                     2020    3
                     2021    5
                     2022    7
        students     2019    2
                     2020    4
                     2021    6
                     2022    8
mumbai  avg_package  2019    0
                     2020    0
                     2021    0
                     2022    0
        students     2019    0
                     2020    0
                     2021    0
                     2022    0
dtype: int64

In [22]:
branch_df3.unstack()

          delhi                                             mumbai            \
    avg_package                students                avg_package
           2019 2020 2021 2022     2019 2020 2021 2022        2019 2020 2021
cse           1    3    5    7        2    4    6    8           0    0    0
ece           9   11   13   15       10   12   14   16           0    0    0


         students
    2022     2019 2020 2021 2022
cse    0        0    0    0    0
ece    0        0    0    0    0

In [23]:
branch_df3.stack()

                      delhi  mumbai
cse 2019 avg_package      1       0
         students         2       0
    2020 avg_package      3       0
         students         4       0
    2021 avg_package      5       0
         students         6       0
    2022 avg_package      7       0
         students         8       0
ece 2019 avg_package      9       0
         students        10       0
    2020 avg_package     11       0
         students        12       0
    2021 avg_package     13       0
         students        14       0
    2022 avg_package     15       0
         students        16       0

**Stack**: Columns <----> Rows :**Unstack**

## **Working with MultiIndex Dataframes**

In [24]:
# head and tail
branch_df3.head()
# shape
branch_df3.shape
# info
branch_df3.info()
# duplicated-- isnull
branch_df3.duplicated()

<class 'pandas.DataFrame'>
MultiIndex: 8 entries, ('cse', np.int64(2019)) to ('ece', np.int64(2022))
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   (delhi, avg_package)   8 non-null      int64
 1   (delhi, students)      8 non-null      int64
 2   (mumbai, avg_package)  8 non-null      int64
 3   (mumbai, students)     8 non-null      int64
dtypes: int64(4)
memory usage: 639.0 bytes

cse  2019    False
     2020    False
     2021    False
     2022    False
ece  2019    False
     2020    False
     2021    False
     2022    False
dtype: bool

In [25]:
branch_df3

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

In [26]:
# Extracting rows single
branch_df3.loc[('cse',2019)]

delhi   avg_package    1
        students       2
mumbai  avg_package    0
        students       0
Name: (cse, 2019), dtype: int64

In [27]:
# multiple
branch_df3.loc[('cse',2019):('ece',2020):2]

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0
    2021           5        6           0        0
ece 2019           9       10           0        0

In [28]:
# Using iloc
branch_df3.iloc[0]

delhi   avg_package    1
        students       2
mumbai  avg_package    0
        students       0
Name: (cse, 2019), dtype: int64

In [29]:
branch_df3.iloc[0:5:2]

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0
    2021           5        6           0        0
ece 2019           9       10           0        0

In [30]:
# Extracting cols
branch_df3['delhi']['students']

cse  2019     2
     2020     4
     2021     6
     2022     8
ece  2019    10
     2020    12
     2021    14
     2022    16
Name: students, dtype: int64

In [31]:
branch_df3.iloc[:,1:3]

            delhi      mumbai
         students avg_package
cse 2019        2           0
    2020        4           0
    2021        6           0
    2022        8           0
ece 2019       10           0
    2020       12           0
    2021       14           0
    2022       16           0

In [32]:
# Extracting Both
branch_df3.iloc[[0,4],[1,2]]

            delhi      mumbai
         students avg_package
cse 2019        2           0
ece 2019       10           0

In [33]:
# sort index
branch_df3.sort_index(ascending=False)

               delhi               mumbai
         avg_package students avg_package students
ece 2022          15       16           0        0
    2021          13       14           0        0
    2020          11       12           0        0
    2019           9       10           0        0
cse 2022           7        8           0        0
    2021           5        6           0        0
    2020           3        4           0        0
    2019           1        2           0        0

In [34]:
# based on one level
branch_df3.sort_index(ascending=[False,True])
branch_df3.sort_index(level=0,ascending=False)

               delhi               mumbai
         avg_package students avg_package students
ece 2022          15       16           0        0
    2021          13       14           0        0
    2020          11       12           0        0
    2019           9       10           0        0
cse 2022           7        8           0        0
    2021           5        6           0        0
    2020           3        4           0        0
    2019           1        2           0        0

In [35]:
# MultipleIndex dataframe(col) ---> transpose
branch_df3.transpose()

                    cse                 ece
                   2019 2020 2021 2022 2019 2020 2021 2022
delhi  avg_package    1    3    5    7    9   11   13   15
       students       2    4    6    8   10   12   14   16
mumbai avg_package    0    0    0    0    0    0    0    0
       students       0    0    0    0    0    0    0    0

In [36]:
# swaplevel
branch_df3.swaplevel(axis=1)

         avg_package students avg_package students
               delhi    delhi      mumbai   mumbai
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

## **Long And Wide Data**
`Wide`: is where we have single row for every data point with multi columns to hold the values of various attributes .<br>
`Long`: is where for each data point we have as many rows as the number of attributes and each row and columns the value of particular attributes  for a given data point.

In [37]:
#  melt -- wide to long
#  pivot --- long to wide

In [38]:
pd.DataFrame({'cse':[120]}).melt()

  variable  value
0      cse    120

In [39]:
pd.DataFrame({'cse':[120],'ece':[100],'mech':[50]}).melt(var_name='Brach',value_name='number_students')

  Brach  number_students
0   cse              120
1   ece              100
2  mech               50

In [40]:
pd.DataFrame(
    {
        'Branch': ['cse','ece','mech'],
        '2020':[100,150,60],
        '2021':[120,130,80],
        '2022':[130,140,70]
    }
).melt(id_vars=['Branch'],var_name='year',value_name='students')

  Branch  year  students
0    cse  2020       100
1    ece  2020       150
2   mech  2020        60
3    cse  2021       120
4    ece  2021       130
5   mech  2021        80
6    cse  2022       130
7    ece  2022       140
8   mech  2022        70

In [41]:
deaths = pd.read_csv(r"C:\Users\LENOVO\Downloads\time_series_covid19_deaths_global.csv")
confirm = pd.read_csv(r"C:\Users\LENOVO\Downloads\time_series_covid19_confirmed_global.csv")

In [42]:
deaths.head()

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/24/22,12/25/22,12/26/22,12/27/22,12/28/22,12/29/22,12/30/22,12/31/22,1/1/23,1/2/23
0,NaN,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,7845,7846,7846,7846,7846,7847,7847,7849,7849,7849
1,NaN,Albania,41.15330,20.168300,0,0,0,0,0,0,...,3595,3595,3595,3595,3595,3595,3595,3595,3595,3595
2,NaN,Algeria,28.03390,1.659600,0,0,0,0,0,0,...,6881,6881,6881,6881,6881,6881,6881,6881,6881,6881
3,NaN,Andorra,42.50630,1.521800,0,0,0,0,0,0,...,165,165,165,165,165,165,165,165,165,165
4,NaN,Angola,-11.20270,17.873900,0,0,0,0,0,0,...,1928,1928,1928,1930,1930,1930,1930,1930,1930,1930

In [43]:
confirm.head()

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/24/22,12/25/22,12/26/22,12/27/22,12/28/22,12/29/22,12/30/22,12/31/22,1/1/23,1/2/23
0,NaN,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,207310,207399,207438,207460,207493,207511,207550,207559,207616,207627
1,NaN,Albania,41.15330,20.168300,0,0,0,0,0,0,...,333749,333749,333751,333751,333776,333776,333806,333806,333811,333812
2,NaN,Algeria,28.03390,1.659600,0,0,0,0,0,0,...,271194,271198,271198,271202,271208,271217,271223,271228,271229,271229
3,NaN,Andorra,42.50630,1.521800,0,0,0,0,0,0,...,47686,47686,47686,47686,47751,47751,47751,47751,47751,47751
4,NaN,Angola,-11.20270,17.873900,0,0,0,0,0,0,...,104973,104973,104973,105095,105095,105095,105095,105095,105095,105095

In [44]:
long_death = deaths.melt(id_vars=['Province/State','Country/Region','Lat','Long'],var_name='Date',value_name='Num_Death')

In [45]:
long_confirm = confirm.melt(id_vars=['Province/State','Country/Region','Lat','Long'],var_name='Date',value_name='Num_cases')

In [48]:
long_death.merge(long_confirm,on=['Date','Province/State','Country/Region','Lat','Long'])[['Country/Region','Date','Num_cases','Num_Death']].head(5)

  Country/Region     Date  Num_cases  Num_Death
0    Afghanistan  1/22/20          0          0
1        Albania  1/22/20          0          0
2        Algeria  1/22/20          0          0
3        Andorra  1/22/20          0          0
4         Angola  1/22/20          0          0