# **DataFrame**

In [227]:
import pandas as pd
import numpy as np

## **Creating DataFrame**

In [228]:
# using list
student_data = [
    [100,80,10],
    [90,70,7],
    [87,76,7.5],
    [85,90,9.6]
]
sd = pd.DataFrame(student_data,columns=['IQ','Marks','Package'])
sd

    IQ  Marks  Package
0  100     80     10.0
1   90     70      7.0
2   87     76      7.5
3   85     90      9.6

In [229]:
# using list
stu_dict = {
    'Name':  ['Rahul','Aman','Kisor','Baldev'],
    'IQ': [90,110,95,89],
    'Marks': [78,89,79,72],
    'package': [9.5,12,9.1,10]
}
stu = pd.DataFrame(stu_dict)
stu.set_index('Name',inplace=True)

In [230]:
#  using read_csv
df = pd.read_csv(r"C:\Users\LENOVO\Downloads\linear_perfect_dataset.csv")
df

     IQ  CGPA  Placed
0    99  7.57       1
1   102  9.26       1
2    83  9.78       0
3   106  6.68       1
4    94  9.51       0
..  ...   ...     ...
95  114  9.74       1
96  122  7.17       1
97  117  8.93       1
98  108  8.24       1
99  122  9.20       1

[100 rows x 3 columns]

In [231]:
df1 = pd.read_csv(r"C:\Users\LENOVO\Downloads\college_student_placement_dataset.csv")
df1

,College_ID,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
0,CLG0030,107,6.61,6.28,8,No,8,8,4,No
1,CLG0061,97,5.52,5.37,8,No,7,8,0,No
2,CLG0036,109,5.36,5.83,9,No,3,1,1,No
3,CLG0055,122,5.47,5.75,6,Yes,1,6,1,No
4,CLG0004,96,7.91,7.69,7,No,8,10,2,No
...,...,...,...,...,...,...,...,...,...,...
9995,CLG0021,119,8.41,8.29,4,No,1,8,0,Yes
9996,CLG0098,70,9.25,9.34,7,No,0,7,2,No
9997,CLG0066,89,6.08,6.25,3,Yes,3,9,5,No
9998,CLG0045,107,8.77,8.92,3,No,7,5,1,No
9999,CLG0060,109,9.41,9.77,8,No,3,5,5,No

## **DataFrame Attributes And Methods**

In [232]:
# Shape
df.shape,df1.shape

((100, 3), (10000, 10))

In [233]:
# dtypes
df.dtypes,df1.dtypes

(IQ          int64
 CGPA      float64
 Placed      int64
 dtype: object,
 College_ID                    str
 IQ                          int64
 Prev_Sem_Result           float64
 CGPA                      float64
 Academic_Performance        int64
 Internship_Experience         str
 Extra_Curricular_Score      int64
 Communication_Skills        int64
 Projects_Completed          int64
 Placement                     str
 dtype: object)

In [234]:
# Index
df.index,df1.index

(RangeIndex(start=0, stop=100, step=1),
 RangeIndex(start=0, stop=10000, step=1))

In [235]:
# Columns
df.columns,df1.columns

(Index(['IQ', 'CGPA', 'Placed'], dtype='str'),
 Index(['College_ID', 'IQ', 'Prev_Sem_Result', 'CGPA', 'Academic_Performance',
        'Internship_Experience', 'Extra_Curricular_Score',
        'Communication_Skills', 'Projects_Completed', 'Placement'],
       dtype='str'))

In [236]:
# Values
sd.values

array([[100. ,  80. ,  10. ],
       [ 90. ,  70. ,   7. ],
       [ 87. ,  76. ,   7.5],
       [ 85. ,  90. ,   9.6]])

In [237]:
#  head and tail
df1.tail()

,College_ID,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
9995,CLG0021,119,8.41,8.29,4,No,1,8,0,Yes
9996,CLG0098,70,9.25,9.34,7,No,0,7,2,No
9997,CLG0066,89,6.08,6.25,3,Yes,3,9,5,No
9998,CLG0045,107,8.77,8.92,3,No,7,5,1,No
9999,CLG0060,109,9.41,9.77,8,No,3,5,5,No

In [238]:
#  Sample()
df.sample()

    IQ  CGPA  Placed
81  85  8.35       0

In [239]:
# info()
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   College_ID              10000 non-null  str
 1   IQ                      10000 non-null  int64
 2   Prev_Sem_Result         10000 non-null  float64
 3   CGPA                    10000 non-null  float64
 4   Academic_Performance    10000 non-null  int64
 5   Internship_Experience   10000 non-null  str
 6   Extra_Curricular_Score  10000 non-null  int64
 7   Communication_Skills    10000 non-null  int64
 8   Projects_Completed      10000 non-null  int64
 9   Placement               10000 non-null  str
dtypes: float64(2), int64(5), str(3)
memory usage: 894.3 KB

In [240]:
# discribe()
df.describe()

               IQ        CGPA      Placed
count  100.000000  100.000000  100.000000
mean   109.520000    7.595800    0.750000
std     16.770272    1.472124    0.435194
min     80.000000    5.030000    0.000000
25%     97.000000    6.297500    0.750000
50%    110.000000    7.735000    1.000000
75%    123.000000    8.827500    1.000000
max    139.000000    9.930000    1.000000

In [241]:
# isnull
df.isnull().sum()

IQ        0
CGPA      0
Placed    0
dtype: int64

In [242]:
# duplicated
df.duplicated().sum()

np.int64(1)

In [243]:
# rename
sd.rename(columns={'Marks': 'Percent','Package':'LPA'}) # inplace False

    IQ  Percent   LPA
0  100       80  10.0
1   90       70   7.0
2   87       76   7.5
3   85       90   9.6

## **Maths Methods**

In [244]:
df.sum(axis=0)

IQ        10952.00
CGPA        759.58
Placed       75.00
dtype: float64

In [245]:
df.mean() , df.median(),df.std(),df.var()

(IQ        109.5200
 CGPA        7.5958
 Placed      0.7500
 dtype: float64,
 IQ        110.000
 CGPA        7.735
 Placed      1.000
 dtype: float64,
 IQ        16.770272
 CGPA       1.472124
 Placed     0.435194
 dtype: float64,
 IQ        281.242020
 CGPA        2.167150
 Placed      0.189394
 dtype: float64)

## **Selecting Cols from a DataFrame**

In [246]:
# single cols....
df1['CGPA']

0       6.28
1       5.37
2       5.83
3       5.75
4       7.69
        ...
9995    8.29
9996    9.34
9997    6.25
9998    8.92
9999    9.77
Name: CGPA, Length: 10000, dtype: float64

In [247]:
df1.head(1)

,College_ID,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
0,CLG0030,107,6.61,6.28,8,No,8,8,4,No

In [248]:
# select Multiple columns.....
df1[['Prev_Sem_Result','CGPA','Academic_Performance']].head() # We Use Fancy Indexing

   Prev_Sem_Result  CGPA  Academic_Performance
0             6.61  6.28                     8
1             5.52  5.37                     8
2             5.36  5.83                     9
3             5.47  5.75                     6
4             7.91  7.69                     7

## **Selecting rows from a DataFrame**
- **iloc** - Searching using index position
- **loc** - Searching using index labels

In [249]:
# single row
df1.iloc[288]

College_ID                CLG0089
IQ                            104
Prev_Sem_Result              9.87
CGPA                         9.58
Academic_Performance            3
Internship_Experience          No
Extra_Curricular_Score          9
Communication_Skills            5
Projects_Completed              0
Placement                      No
Name: 288, dtype: object

In [250]:
# multiple row
df1.iloc[5:15:2]

,College_ID,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
5,CLG0015,96,5.26,5.32,7,No,5,8,0,No
7,CLG0096,111,8.77,8.76,7,No,3,1,2,Yes
9,CLG0057,108,8.82,8.60,4,No,5,9,1,No
11,CLG0077,93,6.23,6.51,8,No,5,7,4,No
13,CLG0017,71,8.74,8.40,6,No,0,5,2,No

In [251]:
# Facncy indexing
df1.iloc[[0,5,7]]

,College_ID,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
0,CLG0030,107,6.61,6.28,8,No,8,8,4,No
5,CLG0015,96,5.26,5.32,7,No,5,8,0,No
7,CLG0096,111,8.77,8.76,7,No,3,1,2,Yes

In [252]:
stu.iloc[0]

IQ         90.0
Marks      78.0
package     9.5
Name: Rahul, dtype: float64

In [253]:
# loc
stu.loc['Baldev'] # index label wise access

IQ         89.0
Marks      72.0
package    10.0
Name: Baldev, dtype: float64

In [254]:
stu.loc[['Baldev','Rahul']]

        IQ  Marks  package
Name
Baldev  89     72     10.0
Rahul   90     78      9.5

## **Selecting Both Rows and Columns**

In [255]:
stu.iloc[0:3,1:3]

       Marks  package
Name
Rahul     78      9.5
Aman      89     12.0
Kisor     79      9.1

In [256]:
stu.loc['Rahul','Marks':]

Marks      78.0
package     9.5
Name: Rahul, dtype: float64

## **Filtering a Dataframe**

In [257]:
ipl = pd.read_csv(r"C:\Users\LENOVO\Downloads\ipl-matches.csv")
ipl.head(3)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough

In [258]:
# find all the final Winners
ipl[['WinningTeam','Season']][(ipl['MatchNumber'] =='Final') ]

               WinningTeam   Season
0           Gujarat Titans     2022
74     Chennai Super Kings     2021
134         Mumbai Indians  2020/21
194         Mumbai Indians     2019
254    Chennai Super Kings     2018
314         Mumbai Indians     2017
373    Sunrisers Hyderabad     2016
433         Mumbai Indians     2015
492  Kolkata Knight Riders     2014
552         Mumbai Indians     2013
628  Kolkata Knight Riders     2012
702    Chennai Super Kings     2011
775    Chennai Super Kings  2009/10
835        Deccan Chargers     2009
892       Rajasthan Royals  2007/08

In [259]:
# how many super over finishes have occured
ipl[['WinningTeam','Season']][(ipl['SuperOver'] == 'Y')].shape[0]

14

In [260]:
#  How Many matches has csk won in kolkata
ipl[(ipl['WinningTeam']=='Chennai Super Kings')& (ipl['City']=='Kolkata')].shape[0]

5

In [264]:
# toss winner is match winner in percentage
s  = ipl[(ipl['TossWinner'] ==ipl['WinningTeam'])].shape[0]
Total = ipl.shape[0]
(s/Total)*100

51.473684210526315

In [266]:
movies = pd.read_csv(r"C:\Users\LENOVO\Downloads\movies.csv")
movies.head(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)

In [269]:
# Movies with rating higher than 8 and votes > 10000
movies[(movies['imdb_rating']> 8) &( movies['imdb_votes'] > 10000)].shape[0]

43

In [288]:
# Action Movies with rating higher than 7.5
mask1 = movies['genres'].str.split('|').apply(lambda x : ('Action' in x))
mask2 = (movies['imdb_rating'] >  7.5)
movies[(mask1) & mask2].shape[0]

33

In [291]:
# or 
mask1 = movies['genres'].str.contains('Action')
mask2 = (movies['imdb_rating'] >  7.5)
movies[(mask1) & mask2].shape[0]

33

In [290]:
# write a function that can return the track record of 2 teams against each other
def track_record():
    return list(zip(ipl['Team1'],ipl['Team2']))
track_record()

[('Rajasthan Royals', 'Gujarat Titans'),
 ('Royal Challengers Bangalore', 'Rajasthan Royals'),
 ('Royal Challengers Bangalore', 'Lucknow Super Giants'),
 ('Rajasthan Royals', 'Gujarat Titans'),
 ('Sunrisers Hyderabad', 'Punjab Kings'),
 ('Delhi Capitals', 'Mumbai Indians'),
 ('Chennai Super Kings', 'Rajasthan Royals'),
 ('Gujarat Titans', 'Royal Challengers Bangalore'),
 ('Lucknow Super Giants', 'Kolkata Knight Riders'),
 ('Sunrisers Hyderabad', 'Mumbai Indians'),
 ('Delhi Capitals', 'Punjab Kings'),
 ('Rajasthan Royals', 'Lucknow Super Giants'),
 ('Chennai Super Kings', 'Gujarat Titans'),
 ('Kolkata Knight Riders', 'Sunrisers Hyderabad'),
 ('Punjab Kings', 'Royal Challengers Bangalore'),
 ('Chennai Super Kings', 'Mumbai Indians'),
 ('Rajasthan Royals', 'Delhi Capitals'),
 ('Gujarat Titans', 'Lucknow Super Giants'),
 ('Kolkata Knight Riders', 'Mumbai Indians'),
 ('Chennai Super Kings', 'Delhi Capitals'),
 ('Royal Challengers Bangalore', 'Sunrisers Hyderabad'),
 ('Lucknow Super Giants', 'Kolkata Knight Riders'),
 ('Punjab Kings', 'Rajasthan Royals'),
 ('Mumbai Indians', 'Gujarat Titans'),
 ('Delhi Capitals', 'Sunrisers Hyderabad'),
 ('Royal Challengers Bangalore', 'Chennai Super Kings'),
 ('Gujarat Titans', 'Punjab Kings'),
 ('Rajasthan Royals', 'Kolkata Knight Riders'),
 ('Chennai Super Kings', 'Sunrisers Hyderabad'),
 ('Lucknow Super Giants', 'Delhi Capitals'),
 ('Rajasthan Royals', 'Mumbai Indians'),
 ('Royal Challengers Bangalore', 'Gujarat Titans'),
 ('Lucknow Super Giants', 'Punjab Kings'),
 ('Kolkata Knight Riders', 'Delhi Capitals'),
 ('Sunrisers Hyderabad', 'Gujarat Titans'),
 ('Rajasthan Royals', 'Royal Challengers Bangalore'),
 ('Punjab Kings', 'Chennai Super Kings'),
 ('Lucknow Super Giants', 'Mumbai Indians'),
 ('Royal Challengers Bangalore', 'Sunrisers Hyderabad'),
 ('Gujarat Titans', 'Kolkata Knight Riders'),
 ('Rajasthan Royals', 'Delhi Capitals'),
 ('Mumbai Indians', 'Chennai Super Kings'),
 ('Punjab Kings', 'Delhi Capitals'),
 ('Royal Challengers Bangalore', 'Lucknow Super Giants'),
 ('Rajasthan Royals', 'Kolkata Knight Riders'),
 ('Chennai Super Kings', 'Gujarat Titans'),
 ('Punjab Kings', 'Sunrisers Hyderabad'),
 ('Royal Challengers Bangalore', 'Delhi Capitals'),
 ('Lucknow Super Giants', 'Mumbai Indians'),
 ('Kolkata Knight Riders', 'Sunrisers Hyderabad'),
 ('Gujarat Titans', 'Rajasthan Royals'),
 ('Punjab Kings', 'Mumbai Indians'),
 ('Chennai Super Kings', 'Royal Challengers Bangalore'),
 ('Gujarat Titans', 'Sunrisers Hyderabad'),
 ('Rajasthan Royals', 'Lucknow Super Giants'),
 ('Delhi Capitals', 'Kolkata Knight Riders'),
 ('Mumbai Indians', 'Royal Challengers Bangalore'),
 ('Chennai Super Kings', 'Sunrisers Hyderabad'),
 ('Punjab Kings', 'Gujarat Titans'),
 ('Delhi Capitals', 'Lucknow Super Giants'),
 ('Mumbai Indians', 'Kolkata Knight Riders'),
 ('Rajasthan Royals', 'Royal Challengers Bangalore'),
 ('Lucknow Super Giants', 'Sunrisers Hyderabad'),
 ('Punjab Kings', 'Chennai Super Kings'),
 ('Gujarat Titans', 'Delhi Capitals'),
 ('Rajasthan Royals', 'Mumbai Indians'),
 ('Punjab Kings', 'Kolkata Knight Riders'),
 ('Chennai Super Kings', 'Lucknow Super Giants'),
 ('Kolkata Knight Riders', 'Royal Challengers Bangalore'),
 ('Rajasthan Royals', 'Sunrisers Hyderabad'),
 ('Lucknow Super Giants', 'Gujarat Titans'),
 ('Royal Challengers Bangalore', 'Punjab Kings'),
 ('Mumbai Indians', 'Delhi Capitals'),
 ('Chennai Super Kings', 'Kolkata Knight Riders'),
 ('Chennai Super Kings', 'Kolkata Knight Riders'),
 ('Delhi Capitals', 'Kolkata Knight Riders'),
 ('Royal Challengers Bangalore', 'Kolkata Knight Riders'),
 ('Delhi Capitals', 'Chennai Super Kings'),
 ('Delhi Capitals', 'Royal Challengers Bangalore'),
 ('Mumbai Indians', 'Sunrisers Hyderabad'),
 ('Kolkata Knight Riders', 'Rajasthan Royals'),
 ('Chennai Super Kings', 'Punjab Kings'),
 ('Sunrisers Hyderabad', 'Royal Challengers Bangalore'),
 ('Rajasthan Royals', 'Mumbai Indians'),
 ('Chennai Super Kings', 'Delhi Capitals'),
 ('Royal Challengers Bangalore', 'Punjab Kings'),
 ('Sunrisers Hyderabad', 'Kolkata Knight Riders'),
 ('Mumbai Indians', 'Delhi Capitals'),
 ('Chennai Super Kings', 'Rajasthan Royals'),
 ('Kolkata Knight Riders', 'Punjab Kings'),
 ('Sunrisers Hyderabad', 'Chennai Super Kings'),
 ('Rajasthan Royals', 'Royal Challengers Bangalore'),
 ('Punjab Kings', 'Mumbai Indians'),
 ('Delhi Capitals', 'Kolkata Knight Riders'),
 ('Rajasthan Royals', 'Sunrisers Hyderabad'),
 ('Kolkata Knight Riders', 'Chennai Super Kings'),
 ('Royal Challengers Bangalore', 'Mumbai Indians'),
 ('Delhi Capitals', 'Rajasthan Royals'),
 ('Punjab Kings', 'Sunrisers Hyderabad'),
 ('Royal Challengers Bangalore', 'Chennai Super Kings'),
 ('Mumbai Indians', 'Kolkata Knight Riders'),
 ('Sunrisers Hyderabad', 'Delhi Capitals'),
 ('Rajasthan Royals', 'Punjab Kings'),
 ('Royal Challengers Bangalore', 'Kolkata Knight Riders'),
 ('Chennai Super Kings', 'Mumbai Indians'),
 ('Punjab Kings', 'Delhi Capitals'),
 ('Rajasthan Royals', 'Sunrisers Hyderabad'),
 ('Chennai Super Kings', 'Mumbai Indians'),
 ('Punjab Kings', 'Royal Challengers Bangalore'),
 ('Kolkata Knight Riders', 'Delhi Capitals'),
 ('Rajasthan Royals', 'Mumbai Indians'),
 ('Sunrisers Hyderabad', 'Chennai Super Kings'),
 ('Royal Challengers Bangalore', 'Delhi Capitals'),
 ('Punjab Kings', 'Kolkata Knight Riders'),
 ('Delhi Capitals', 'Sunrisers Hyderabad'),
 ('Chennai Super Kings', 'Royal Challengers Bangalore'),
 ('Kolkata Knight Riders', 'Rajasthan Royals'),
 ('Mumbai Indians', 'Punjab Kings'),
 ('Rajasthan Royals', 'Royal Challengers Bangalore'),
 ('Chennai Super Kings', 'Kolkata Knight Riders'),
 ('Punjab Kings', 'Sunrisers Hyderabad'),
 ('Mumbai Indians', 'Delhi Capitals'),
 ('Chennai Super Kings', 'Rajasthan Royals'),
 ('Punjab Kings', 'Delhi Capitals'),
 ('Royal Challengers Bangalore', 'Kolkata Knight Riders'),
 ('Mumbai Indians', 'Sunrisers Hyderabad'),
 ('Punjab Kings', 'Chennai Super Kings'),
 ('Delhi Capitals', 'Rajasthan Royals'),
 ('Royal Challengers Bangalore', 'Sunrisers Hyderabad'),
 ('Mumbai Indians', 'Kolkata Knight Riders'),
 ('Punjab Kings', 'Rajasthan Royals'),
 ('Kolkata Knight Riders', 'Sunrisers Hyderabad'),
 ('Chennai Super Kings', 'Delhi Capitals'),
 ('Mumbai Indians', 'Royal Challengers Bangalore'),
 ('Delhi Capitals', 'Mumbai Indians'),
 ('Delhi Capitals', 'Sunrisers Hyderabad'),
 ('Royal Challengers Bangalore', 'Sunrisers Hyderabad'),
 ('Mumbai Indians', 'Delhi Capitals'),
 ('Mumbai Indians', 'Sunrisers Hyderabad'),
 ('Royal Challengers Bangalore', 'Delhi Capitals'),
 ('Kolkata Knight Riders', 'Rajasthan Royals'),
 ('Kings XI Punjab', 'Chennai Super Kings'),
 ('Delhi Capitals', 'Mumbai Indians'),
 ('Royal Challengers Bangalore', 'Sunrisers Hyderabad'),
 ('Kings XI Punjab', 'Rajasthan Royals'),
 ('Kolkata Knight Riders', 'Chennai Super Kings'),
 ('Royal Challengers Bangalore', 'Mumbai Indians'),
 ('Sunrisers Hyderabad', 'Delhi Capitals'),
 ('Kolkata Knight Riders', 'Kings XI Punjab'),
 ('Mumbai Indians', 'Rajasthan Royals'),
 ('Royal Challengers Bangalore', 'Chennai Super Kings'),
 ('Kings XI Punjab', 'Sunrisers Hyderabad'),
 ('Kolkata Knight Riders', 'Delhi Capitals'),
 ('Chennai Super Kings', 'Mumbai Indians'),
 ('Rajasthan Royals', 'Sunrisers Hyderabad'),
 ('Kolkata Knight Riders', 'Royal Challengers Bangalore'),
 ('Delhi Capitals', 'Kings XI Punjab'),
 ('Chennai Super Kings', 'Rajasthan Royals'),
 ('Kolkata Knight Riders', 'Sunrisers Hyderabad'),
 ('Mumbai Indians', 'Kings XI Punjab'),
 ('Rajasthan Royals', 'Royal Challengers Bangalore'),
 ('Chennai Super Kings', 'Delhi Capitals'),
 ('Kolkata Knight Riders', 'Mumbai Indians'),
 ('Royal Challengers Bangalore', 'Kings XI Punjab'),
 ('Delhi Capitals', 'Rajasthan Royals'),
 ('Chennai Super Kings', 'Sunrisers Hyderabad'),
 ('Royal Challengers Bangalore', 'Kolkata Knight Riders'),
 ('Sunrisers Hyderabad', 'Rajasthan Royals'),
 ('Delhi Capitals', 'Mumbai Indians'),
 ('Kolkata Knight Riders', 'Kings XI Punjab'),
 ('Royal Challengers Bangalore', 'Chennai Super Kings'),
 ('Delhi Capitals', 'Rajasthan Royals'),
 ('Sunrisers Hyderabad', 'Kings XI Punjab'),
 ('Kolkata Knight Riders', 'Chennai Super Kings'),
 ('Mumbai Indians', 'Rajasthan Royals'),
 ('Delhi Capitals', 'Royal Challengers Bangalore'),
 ('Kings XI Punjab', 'Chennai Super Kings'),
 ('Mumbai Indians', 'Sunrisers Hyderabad'),
 ('Rajasthan Royals', 'Royal Challengers Bangalore'),
 ('Delhi Capitals', 'Kolkata Knight Riders'),
 ('Sunrisers Hyderabad', 'Chennai Super Kings'),
 ('Mumbai Indians', 'Kings XI Punjab'),
 ('Kolkata Knight Riders', 'Rajasthan Royals'),
 ('Sunrisers Hyderabad', 'Delhi Capitals'),
 ('Royal Challengers Bangalore', 'Mumbai Indians'),
 ('Kings XI Punjab', 'Rajasthan Royals'),
 ('Sunrisers Hyderabad', 'Kolkata Knight Riders'),
 ('Delhi Capitals', 'Chennai Super Kings'),
 ('Kings XI Punjab', 'Royal Challengers Bangalore'),
 ('Mumbai Indians', 'Kolkata Knight Riders'),
 ('Rajasthan Royals', 'Chennai Super Kings'),
 ('Royal Challengers Bangalore', 'Sunrisers Hyderabad'),
 ('Delhi Capitals', 'Kings XI Punjab'),
 ('Mumbai Indians', 'Chennai Super Kings'),
 ('Mumbai Indians', 'Chennai Super Kings'),
 ('Delhi Capitals', 'Chennai Super Kings'),
 ('Sunrisers Hyderabad', 'Delhi Capitals'),
 ('Chennai Super Kings', 'Mumbai Indians'),
 ('Chennai Super Kings', 'Kings XI Punjab'),
 ('Kolkata Knight Riders', 'Mumbai Indians'),
 ('Sunrisers Hyderabad', 'Royal Challengers Bangalore'),
 ('Rajasthan Royals', 'Delhi Capitals'),
 ('Kings XI Punjab', 'Kolkata Knight Riders'),
 ('Mumbai Indians', 'Sunrisers Hyderabad'),
 ('Chennai Super Kings', 'Delhi Capitals'),
 ('Royal Challengers Bangalore', 'Rajasthan Royals'),
 ('Sunrisers Hyderabad', 'Kings XI Punjab'),
 ('Kolkata Knight Riders', 'Mumbai Indians'),
 ('Delhi Capitals', 'Royal Challengers Bangalore'),
 ('Sunrisers Hyderabad', 'Rajasthan Royals'),
 ('Mumbai Indians', 'Chennai Super Kings'),
 ('Kolkata Knight Riders', 'Rajasthan Royals'),
 ('Royal Challengers Bangalore', 'Kings XI Punjab'),
 ('Sunrisers Hyderabad', 'Chennai Super Kings'),
 ('Rajasthan Royals', 'Delhi Capitals'),
 ('Kolkata Knight Riders', 'Sunrisers Hyderabad'),
 ('Royal Challengers Bangalore', 'Chennai Super Kings'),
 ('Kings XI Punjab', 'Delhi Capitals'),
 ('Mumbai Indians', 'Rajasthan Royals'),
 ('Royal Challengers Bangalore', 'Kolkata Knight Riders'),
 ('Mumbai Indians', 'Delhi Capitals'),
 ('Chennai Super Kings', 'Sunrisers Hyderabad'),
 ('Kings XI Punjab', 'Rajasthan Royals'),
 ('Royal Challengers Bangalore', 'Mumbai Indians'),
 ('Kolkata Knight Riders', 'Chennai Super Kings'),
 ('Delhi Capitals', 'Sunrisers Hyderabad'),
 ('Mumbai Indians', 'Rajasthan Royals'),
 ('Kings XI Punjab', 'Royal Challengers Bangalore'),
 ('Kolkata Knight Riders', 'Delhi Capitals'),
 ('Rajasthan Royals', 'Chennai Super Kings'),
 ('Kings XI Punjab', 'Mumbai Indians'),
 ('Kolkata Knight Riders', 'Chennai Super Kings'),
 ('Sunrisers Hyderabad', 'Kings XI Punjab'),
 ('Rajasthan Royals', 'Kolkata Knight Riders'),
 ('Royal Challengers Bangalore', 'Delhi Capitals'),
 ('Mumbai Indians', 'Sunrisers Hyderabad'),
 ('Chennai Super Kings', 'Kings XI Punjab'),
 ('Royal Challengers Bangalore', 'Kolkata Knight Riders'),
 ('Delhi Capitals', 'Sunrisers Hyderabad'),
 ('Mumbai Indians', 'Chennai Super Kings'),
 ('Royal Challengers Bangalore', 'Rajasthan Royals'),
 ('Kings XI Punjab', 'Delhi Capitals'),
 ('Sunrisers Hyderabad', 'Royal Challengers Bangalore'),
 ('Chennai Super Kings', 'Rajasthan Royals'),
 ('Kolkata Knight Riders', 'Delhi Capitals'),
 ('Mumbai Indians', 'Kings XI Punjab'),
 ('Rajasthan Royals', 'Sunrisers Hyderabad'),
 ('Mumbai Indians', 'Royal Challengers Bangalore'),
 ('Kolkata Knight Riders', 'Kings XI Punjab'),
 ('Delhi Capitals', 'Chennai Super Kings'),
 ('Kings XI Punjab', 'Rajasthan Royals'),
 ('Delhi Capitals', 'Mumbai Indians'),
 ('Sunrisers Hyderabad', 'Kolkata Knight Riders'),
 ('Royal Challengers Bangalore', 'Chennai Super Kings'),
 ('Sunrisers Hyderabad', 'Chennai Super Kings'),
 ('Sunrisers Hyderabad', 'Kolkata Knight Riders'),
 ('Kolkata Knight Riders', 'Rajasthan Royals'),
 ('Sunrisers Hyderabad', 'Chennai Super Kings'),
 ('Kings XI Punjab', 'Chennai Super Kings'),
 ('Delhi Daredevils', 'Mumbai Indians'),
 ('Sunrisers Hyderabad', 'Kolkata Knight Riders'),
 ('Rajasthan Royals', 'Royal Challengers Bangalore'),
 ('Delhi Daredevils', 'Chennai Super Kings'),
 ('Royal Challengers Bangalore', 'Sunrisers Hyderabad'),
 ('Mumbai Indians', 'Kings XI Punjab'),
 ('Rajasthan Royals', 'Kolkata Knight Riders'),
 ('Kings XI Punjab', 'Royal Challengers Bangalore'),
 ('Mumbai Indians', 'Rajasthan Royals'),
 ('Sunrisers Hyderabad', 'Chennai Super Kings'),
 ('Delhi Daredevils', 'Royal Challengers Bangalore'),
 ('Kolkata Knight Riders', 'Kings XI Punjab'),
 ('Chennai Super Kings', 'Rajasthan Royals'),
 ('Delhi Daredevils', 'Sunrisers Hyderabad'),
 ('Mumbai Indians', 'Kolkata Knight Riders'),
 ('Rajasthan Royals', 'Kings XI Punjab'),
 ('Sunrisers Hyderabad', 'Royal Challengers Bangalore'),
 ('Rajasthan Royals', 'Kings XI Punjab'),
 ('Mumbai Indians', 'Kolkata Knight Riders'),
 ('Delhi Daredevils', 'Sunrisers Hyderabad'),
 ('Royal Challengers Bangalore', 'Chennai Super Kings'),
 ('Kings XI Punjab', 'Mumbai Indians'),
 ('Chennai Super Kings', 'Kolkata Knight Riders'),
 ('Delhi Daredevils', 'Rajasthan Royals'),
 ('Royal Challengers Bangalore', 'Mumbai Indians'),
 ('Chennai Super Kings', 'Delhi Daredevils'),
 ('Sunrisers Hyderabad', 'Rajasthan Royals'),
 ('Royal Challengers Bangalore', 'Kolkata Knight Riders'),
 ('Chennai Super Kings', 'Mumbai Indians'),
 ('Delhi Daredevils', 'Kolkata Knight Riders'),
 ('Sunrisers Hyderabad', 'Kings XI Punjab'),
 ('Royal Challengers Bangalore', 'Chennai Super Kings'),
 ('Sunrisers Hyderabad', 'Mumbai Indians'),
 ('Kings XI Punjab', 'Delhi Daredevils'),
 ('Mumbai Indians', 'Rajasthan Royals'),
 ('Chennai Super Kings', 'Sunrisers Hyderabad'),
 ('Delhi Daredevils', 'Royal Challengers Bangalore'),
 ('Kolkata Knight Riders', 'Kings XI Punjab'),
 ('Chennai Super Kings', 'Rajasthan Royals'),
 ('Kings XI Punjab', 'Sunrisers Hyderabad'),
 ('Rajasthan Royals', 'Kolkata Knight Riders'),
 ('Mumbai Indians', 'Royal Challengers Bangalore'),
 ('Kolkata Knight Riders', 'Delhi Daredevils'),
 ('Kings XI Punjab', 'Chennai Super Kings'),
 ('Rajasthan Royals', 'Royal Challengers Bangalore'),
 ('Kolkata Knight Riders', 'Sunrisers Hyderabad'),
 ('Mumbai Indians', 'Delhi Daredevils'),
 ('Kings XI Punjab', 'Royal Challengers Bangalore'),
 ('Mumbai Indians', 'Sunrisers Hyderabad'),
 ('Rajasthan Royals', 'Delhi Daredevils'),
 ('Kolkata Knight Riders', 'Chennai Super Kings'),
 ('Rajasthan Royals', 'Sunrisers Hyderabad'),
 ('Delhi Daredevils', 'Kings XI Punjab'),
 ('Royal Challengers Bangalore', 'Kolkata Knight Riders'),
 ('Mumbai Indians', 'Chennai Super Kings'),
 ('Mumbai Indians', 'Rising Pune Supergiant'),
 ('Mumbai Indians', 'Kolkata Knight Riders'),
 ('Sunrisers Hyderabad', 'Kolkata Knight Riders'),
 ('Mumbai Indians', 'Rising Pune Supergiant'),
 ('Delhi Daredevils', 'Royal Challengers Bangalore'),
 ('Rising Pune Supergiant', 'Kings XI Punjab'),
 ('Kolkata Knight Riders', 'Mumbai Indians'),
 ('Gujarat Lions', 'Sunrisers Hyderabad'),
 ('Delhi Daredevils', 'Rising Pune Supergiant'),
 ('Mumbai Indians', 'Kings XI Punjab'),
 ('Gujarat Lions', 'Delhi Daredevils'),
 ('Kings XI Punjab', 'Kolkata Knight Riders'),
 ('Sunrisers Hyderabad', 'Mumbai Indians'),
 ('Royal Challengers Bangalore', 'Kolkata Knight Riders'),
 ('Kings XI Punjab', 'Gujarat Lions'),
 ('Delhi Daredevils', 'Mumbai Indians'),
 ('Sunrisers Hyderabad', 'Rising Pune Supergiant'),
 ('Royal Challengers Bangalore', 'Kings XI Punjab'),
 ('Delhi Daredevils', 'Gujarat Lions'),
 ('Kolkata Knight Riders', 'Rising Pune Supergiant'),
 ('Delhi Daredevils', 'Sunrisers Hyderabad'),
 ('Rising Pune Supergiant', 'Gujarat Lions'),
 ('Mumbai Indians', 'Royal Challengers Bangalore'),
 ('Sunrisers Hyderabad', 'Kolkata Knight Riders'),
 ('Kings XI Punjab', 'Delhi Daredevils'),
 ('Gujarat Lions', 'Mumbai Indians'),
 ('Rising Pune Supergiant', 'Royal Challengers Bangalore'),
 ('Kolkata Knight Riders', 'Delhi Daredevils'),
 ('Kings XI Punjab', 'Sunrisers Hyderabad'),
 ('Royal Challengers Bangalore', 'Gujarat Lions'),
 ('Rising Pune Supergiant', 'Kolkata Knight Riders'),
 ('Mumbai Indians', 'Rising Pune Supergiant'),
 ('Kolkata Knight Riders', 'Royal Challengers Bangalore'),
 ('Gujarat Lions', 'Kings XI Punjab'),
 ('Rising Pune Supergiant', 'Sunrisers Hyderabad'),
 ('Mumbai Indians', 'Delhi Daredevils'),
 ('Kolkata Knight Riders', 'Gujarat Lions'),
 ('Kings XI Punjab', 'Mumbai Indians'),
 ('Sunrisers Hyderabad', 'Delhi Daredevils'),
 ('Gujarat Lions', 'Royal Challengers Bangalore'),
 ('Delhi Daredevils', 'Kolkata Knight Riders'),
 ('Sunrisers Hyderabad', 'Kings XI Punjab'),
 ('Royal Challengers Bangalore', 'Rising Pune Supergiant'),
 ('Mumbai Indians', 'Gujarat Lions'),
 ('Delhi Daredevils', 'Kings XI Punjab'),
 ('Kolkata Knight Riders', 'Sunrisers Hyderabad'),
 ('Gujarat Lions', 'Rising Pune Supergiant'),
 ('Royal Challengers Bangalore', 'Mumbai Indians'),
 ('Kolkata Knight Riders', 'Kings XI Punjab'),
 ('Mumbai Indians', 'Sunrisers Hyderabad'),
 ('Rising Pune Supergiant', 'Delhi Daredevils'),
 ('Kings XI Punjab', 'Royal Challengers Bangalore'),
 ('Mumbai Indians', 'Kolkata Knight Riders'),
 ('Sunrisers Hyderabad', 'Gujarat Lions'),
 ('Royal Challengers Bangalore', 'Delhi Daredevils'),
 ('Kings XI Punjab', 'Rising Pune Supergiant'),
 ('Gujarat Lions', 'Kolkata Knight Riders'),
 ('Rising Pune Supergiant', 'Mumbai Indians'),
 ('Sunrisers Hyderabad', 'Royal Challengers Bangalore'),
 ('Royal Challengers Bangalore', 'Sunrisers Hyderabad'),
 ('Gujarat Lions', 'Sunrisers Hyderabad'),
 ('Sunrisers Hyderabad', 'Kolkata Knight Riders'),
 ('Gujarat Lions', 'Royal Challengers Bangalore'),
 ('Delhi Daredevils', 'Royal Challengers Bangalore'),
 ('Kolkata Knight Riders', 'Sunrisers Hyderabad'),
 ('Gujarat Lions', 'Mumbai Indians'),
 ('Rising Pune Supergiants', 'Kings XI Punjab'),
 ('Delhi Daredevils', 'Sunrisers Hyderabad'),
 ('Gujarat Lions', 'Kolkata Knight Riders'),
 ('Royal Challengers Bangalore', 'Kings XI Punjab'),
 ('Rising Pune Supergiants', 'Delhi Daredevils'),
 ('Kolkata Knight Riders', 'Royal Challengers Bangalore'),
 ('Kings XI Punjab', 'Sunrisers Hyderabad'),
 ('Mumbai Indians', 'Delhi Daredevils'),
 ('Royal Challengers Bangalore', 'Gujarat Lions'),
 ('Kolkata Knight Riders', 'Rising Pune Supergiants'),
 ('Mumbai Indians', 'Kings XI Punjab'),
 ('Sunrisers Hyderabad', 'Delhi Daredevils'),
 ('Royal Challengers Bangalore', 'Mumbai Indians'),
 ('Rising Pune Supergiants', 'Sunrisers Hyderabad'),
 ('Kings XI Punjab', 'Royal Challengers Bangalore'),
 ('Kolkata Knight Riders', 'Gujarat Lions'),
 ('Mumbai Indians', 'Sunrisers Hyderabad'),
 ('Kings XI Punjab', 'Delhi Daredevils'),
 ('Royal Challengers Bangalore', 'Rising Pune Supergiants'),
 ('Sunrisers Hyderabad', 'Gujarat Lions'),
 ('Delhi Daredevils', 'Rising Pune Supergiants'),
 ('Kolkata Knight Riders', 'Kings XI Punjab'),
 ('Gujarat Lions', 'Delhi Daredevils'),
 ('Royal Challengers Bangalore', 'Kolkata Knight Riders'),
 ('Gujarat Lions', 'Kings XI Punjab'),
 ('Rising Pune Supergiants', 'Mumbai Indians'),
 ('Delhi Daredevils', 'Kolkata Knight Riders'),
 ('Sunrisers Hyderabad', 'Royal Challengers Bangalore'),
 ('Rising Pune Supergiants', 'Gujarat Lions'),
 ('Mumbai Indians', 'Kolkata Knight Riders'),
 ('Delhi Daredevils', 'Gujarat Lions'),
 ('Sunrisers Hyderabad', 'Rising Pune Supergiants'),
 ('Kings XI Punjab', 'Mumbai Indians'),
 ('Rising Pune Supergiants', 'Kolkata Knight Riders'),
 ('Gujarat Lions', 'Royal Challengers Bangalore'),
 ('Sunrisers Hyderabad', 'Kings XI Punjab'),
 ('Delhi Daredevils', 'Mumbai Indians'),
 ('Rising Pune Supergiants', 'Royal Challengers Bangalore'),
 ('Gujarat Lions', 'Sunrisers Hyderabad'),
 ('Mumbai Indians', 'Royal Challengers Bangalore'),
 ('Kings XI Punjab', 'Kolkata Knight Riders'),
 ('Sunrisers Hyderabad', 'Mumbai Indians'),
 ('Royal Challengers Bangalore', 'Delhi Daredevils'),

## **Adding new cols**

In [292]:
# compleatly new
movies['countary'] = 'India'

In [294]:
movies.head(3)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date,countary
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA),India
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India),India
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA),India

In [301]:
# from existing onces
movies.dropna(inplace=True)
movies['LeadActor']= movies['actors'].str.split('|').apply(lambda x: x[0])
movies.head(3)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date,countary,LeadActor
11,Gully Boy,tt2395469,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gully_Boy,Gully Boy,Gully Boy,0,2019,153,Drama|Music,8.2,22440,"Gully Boy is a film about a 22-year-old boy ""M...",A coming-of-age story based on the lives of st...,Apna Time Aayega!,Ranveer Singh|Alia Bhatt|Siddhant Chaturvedi|V...,6 wins & 3 nominations,14 February 2019 (USA),India,Ranveer Singh
34,Yeh Hai India,tt5525846,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Hai_India,Yeh Hai India,Yeh Hai India,0,2017,128,Action|Adventure|Drama,5.7,169,Yeh Hai India follows the story of a 25 years...,Yeh Hai India follows the story of a 25 years...,A Film for Every Indian,Gavie Chahal|Mohan Agashe|Mohan Joshi|Lom Harsh|,2 wins & 1 nomination,24 May 2019 (India),India,Gavie Chahal
37,Article 15 (film),tt10324144,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Article_15_(film),Article 15,Article 15,0,2019,130,Crime|Drama,8.3,13417,In the rural heartlands of India an upright p...,In the rural heartlands of India an upright p...,Farq Bahut Kar Liya| Ab Farq Laayenge.,Ayushmann Khurrana|Nassar|Manoj Pahwa|Kumud Mi...,1 win,28 June 2019 (USA),India,Ayushmann Khurrana

## **Important DataFrame Functions**

In [313]:
ipl.info()

<class 'pandas.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int32
 1   City             899 non-null    str
 2   Date             950 non-null    str
 3   Season           950 non-null    category
 4   MatchNumber      950 non-null    str
 5   Team1            950 non-null    str
 6   Team2            950 non-null    str
 7   Venue            950 non-null    str
 8   TossWinner       950 non-null    str
 9   TossDecision     950 non-null    str
 10  SuperOver        946 non-null    str
 11  WinningTeam      946 non-null    str
 12  WonBy            950 non-null    str
 13  Margin           932 non-null    float32
 14  method           19 non-null     str
 15  Player_of_Match  946 non-null    str
 16  Team1Players     950 non-null    str
 17  Team2Players     950 non-null    str
 18  Umpire1          950 non-null    str
 19  Umpire2          950 non-null    str
dtypes: category(1), float32(1), int32(1), str(17)
memory usage: 558.2 KB

In [314]:
# astype
ipl['ID'] = ipl['ID'].astype('int32')
ipl['Margin'] = ipl['Margin'].astype('float32')
ipl['Season'] = ipl['Season'].astype('category')

In [ ]:
# values_counts